package controller

import (
	"net/http"

	"house-app/models"
	"house-app/service"

	"github.com/gin-gonic/gin"

	_ "house-app/docs" // docs is generated by Swag CLI

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// APIServer holds the service and router
type APIServer struct {
	service *service.Service
	router  *gin.Engine
}

// NewAPIServer creates a new API server
func NewAPIServer(service *service.Service) *APIServer {
	router := gin.Default()

	s := &APIServer{
		service: service,
		router:  router,
	}

	v1 := router.Group("/api/v1")
	{
		images := v1.Group("/images")
		{
			images.POST("/", s.UploadImage)
			images.GET("/", s.GetImages)
			images.GET("/search", s.SearchImages)
			images.POST("/bulk-upload", s.BulkUploadImages)
		}
	}

	// Swagger endpoint
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	return s
}

// Run starts the API server
func (s *APIServer) Run(addr string) {
	s.router.Run(addr)
}

// UploadImage godoc
// @Summary Upload a single image
// @Description Upload a single image file
// @Tags images
// @Accept  multipart/form-data
// @Produce  json
// @Param file formData file true "Image file to upload"
// @Param tags formData string false "Comma-separated tags"
// @Success 201 {object} models.Image
// @Router /images [post]
func (s *APIServer) UploadImage(c *gin.Context) {
	file, err := c.FormFile("file")
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "No file provided"})
		return
	}

	// Parse tags if provided
	tagsStr := c.PostForm("tags")
	var tags []string
	if tagsStr != "" {
		// Simple comma-separated parsing
		tags = []string{tagsStr}
	}

	image, err := s.service.UploadImage(file, tags)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusCreated, image)
}

// GetImages godoc
// @Summary Get all images
// @Description Get a list of all images
// @Tags images
// @Produce  json
// @Success 200 {array} models.Image
// @Router /images [get]
func (s *APIServer) GetImages(c *gin.Context) {
	images, err := s.service.GetImages()
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Error fetching images"})
		return
	}
	c.JSON(http.StatusOK, images)
}

// SearchImages godoc
// @Summary Search images
// @Description Search for images by filename or tags. Requires a text index on the collection.
// @Tags images
// @Produce  json
// @Param q query string true "Search query"
// @Success 200 {array} models.Image
// @Router /images/search [get]
func (s *APIServer) SearchImages(c *gin.Context) {
	query := c.Query("q")
	if query == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "Query parameter 'q' is required"})
		return
	}

	images, err := s.service.SearchImages(query)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Error searching images"})
		return
	}

	c.JSON(http.StatusOK, images)
}

// BulkUploadImages godoc
// @Summary Bulk upload images from a source folder
// @Description Upload multiple images from a specified folder path
// @Tags images
// @Accept  json
// @Produce  json
// @Param request body models.BulkUploadRequest true "Bulk upload request"
// @Success 200 {object} models.BulkUploadResponse
// @Router /images/bulk-upload [post]
func (s *APIServer) BulkUploadImages(c *gin.Context) {
	var req models.BulkUploadRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	if req.SourceFolder == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "sourceFolder is required"})
		return
	}

	result, err := s.service.BulkUploadImages(req.SourceFolder, req.Tags)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, result)
}
